- 넘파이 실습


In [110]:
math=[67,43,14,89,50] #수학점수
eng=[78,98,56,87,44] #영어점수

math+eng

[67, 43, 14, 89, 50, 78, 98, 56, 87, 44]

In [111]:
# 리스트로 합 구하기
hap=[]
for i in range(len(math)): #0,1,2,3,4
    hap.append(math[i]+eng[i])

hap

[145, 141, 70, 176, 94]

In [112]:
# 넘파이 배열로 합구하기
import numpy as np

mathNum=np.array(math)
engNum=np.array(eng)

print(mathNum)
engNum

[67 43 14 89 50]


array([78, 98, 56, 87, 44])

In [113]:
mathNum+engNum

array([145, 141,  70, 176,  94])

__bmi 구하기__

In [114]:
heights=[1.68,1.76,1.59,1.86,1.73] #키 (단위:m)
weights=[70,82,85,92,79] #몸무게 (단위:kg)

np_heights=np.array(heights)
np_weights=np.array(weights)

bmi=np_weights/(np_heights**2)
print('대상자 bmi')
bmi


대상자 bmi


array([24.8015873 , 26.47210744, 33.62208773, 26.59266967, 26.3958034 ])

__pandas 예제실습__

In [115]:
#series 생성
import pandas as pd

num=[i for i in range(1,11)]

seriesNum=pd.Series(num)
seriesNum

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [116]:
# series 요약통계

seriesNum.sum()
seriesNum.mean()
seriesNum.std()
seriesNum.median()

seriesNum.describe() #요약통계


count    10.00000
mean      5.50000
std       3.02765
min       1.00000
25%       3.25000
50%       5.50000
75%       7.75000
max      10.00000
dtype: float64

In [117]:
# 딕셔너리 =>시리즈
num2=pd.Series({'a':1,'b':2,'c':3,'d':4})
num2

a    1
b    2
c    3
d    4
dtype: int64

In [118]:
num2[0]    #인덱스 번호로 추출
num2['c']  #인덱스 이름으로 추출

/tmp/ipykernel_1524/3773875624.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  num2[0]    #인덱스 번호로 추출


3

- 결측치 확인

In [119]:
s=pd.Series([1,2,np.nan,4,5])
s

0    1.0
1    2.0
2    NaN
3    4.0
4    5.0
dtype: float64

In [120]:
#결측지 확인
s.isnull()
s.isnull().sum()

1

In [121]:
#결측치 처리_ 채워넣기
s.fillna(0) #원본저장x
s.fillna(0,inplace=True) #원본저장o
s


0    1.0
1    2.0
2    0.0
3    4.0
4    5.0
dtype: float64

In [122]:
#결측치처리 삭제
a=pd.Series([1,2,np.nan,4,5,7,np.nan])
a

0    1.0
1    2.0
2    NaN
3    4.0
4    5.0
5    7.0
6    NaN
dtype: float64

In [123]:
a.dropna()

0    1.0
1    2.0
3    4.0
4    5.0
5    7.0
dtype: float64

- DataFrame 생성

In [124]:
# dataframe 생성

nums=[[1,2,3],[4,5,6],[7,8,9]]
dfnums=pd.DataFrame(nums)
dfnums

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [125]:
# 정보
dfnums.shape #행렬 정보
dfnums.shape[0] 
dfnums[0].sum()

12

In [126]:
#행, 열별로 합계 구하기
dfnums.sum(axis=1) # 가로방향 각 행별 합계
dfnums.sum(axis=0) # 세로방향 각 행별 합계

0    12
1    15
2    18
dtype: int64

- 컬럼명 생성

In [127]:
users=[['철수',160,16],['민수',170,18],['짱구',130,13],['영희',110,8]]
dfusers=pd.DataFrame(users)
dfusers

0    1   2
0  철수  160  16
1  민수  170  18
2  짱구  130  13
3  영희  110   8

In [128]:
# 컬럼명 생성

dfusers.columns=['name','height','age']
dfusers

name  height  age
0   철수     160   16
1   민수     170   18
2   짱구     130   13
3   영희     110    8

In [129]:
# 인덱스명 생성

dfusers.index=('학생1','학생2','학생3','학생4')
dfusers

name  height  age
학생1   철수     160   16
학생2   민수     170   18
학생3   짱구     130   13
학생4   영희     110    8

In [130]:
dfusers['height'].sum()

570

- 인덱스로 행추출

In [131]:
# 인덱스명으로 행 추출

dfusers.loc['학생1']
dfusers.loc[['학생1','학생3']]
dfusers.loc['학생1','age']
dfusers.loc['학생3',['name','age']]

name    짱구
age     13
Name: 학생3, dtype: object

In [132]:
# 인덱스번호로 행 추출

dfusers.iloc[0]
dfusers.iloc[[0,2]]
dfusers.iloc[0,0]
dfusers.iloc[0,[0,0]]

name    철수
name    철수
Name: 학생1, dtype: object

- 새로운 열 생성


In [133]:
#새로운 열생성
dfusers['weight']=[80,67,30,17]
dfusers

name  height  age  weight
학생1   철수     160   16      80
학생2   민수     170   18      67
학생3   짱구     130   13      30
학생4   영희     110    8      17

In [134]:
# 새로운 열생성(위치지정)
dfusers.insert(2,'Type',['A','B','O','AB'])
dfusers

name  height Type  age  weight
학생1   철수     160    A   16      80
학생2   민수     170    B   18      67
학생3   짱구     130    O   13      30
학생4   영희     110   AB    8      17

In [135]:
# 부울링 인덱싱

dfusers['height'] >= 150
dfusers['Type']== 'A'
dfusers[dfusers['Type']=='A']

name  height Type  age  weight
학생1   철수     160    A   16      80

In [136]:
(dfusers['height'] >= 150) & (dfusers['weight'] <= 70) #and
(dfusers['height'] >= 150) | (dfusers['weight'] <= 70) #or

학생1    True
학생2    True
학생3    True
학생4    True
dtype: bool

In [137]:
# 정렬
dfusers.sort_values(by='age') # 오름차순
dfusers.sort_values(by='age',ascending=False) #내림차순

name  height Type  age  weight
학생2   민수     170    B   18      67
학생1   철수     160    A   16      80
학생3   짱구     130    O   13      30
학생4   영희     110   AB    8      17

In [138]:
# 열 삭제

dfusers.drop('age',axis=1, inplace=True)
dfusers

name  height Type  weight
학생1   철수     160    A      80
학생2   민수     170    B      67
학생3   짱구     130    O      30
학생4   영희     110   AB      17

In [139]:
del dfusers['Type']
dfusers

name  height  weight
학생1   철수     160      80
학생2   민수     170      67
학생3   짱구     130      30
학생4   영희     110      17

In [158]:
user1=[['Alice',24,'New Yock'],['Bob',24,'LOS Angeles'],['Charlie',22,'Chicago'],['David',32,'Houston'],['Eve',29,'Phoenix']]
dfuser1=pd.DataFrame(user1)
dfuser1
dfuser1.columns=['name','age','city']
dfuser1


name  age         city
0    Alice   24     New Yock
1      Bob   24  LOS Angeles
2  Charlie   22      Chicago
3    David   32      Houston
4      Eve   29      Phoenix

In [155]:
dfuser1['score']=[85,90,78,92,88]
dfuser1

name  age         city  score
0    Alice   24     New Yock     85
1      Bob   24  LOS Angeles     90
2  Charlie   22      Chicago     78
3    David   32      Houston     92
4      Eve   29      Phoenix     88

In [153]:
filter_df = dfuser1[dfuser1['age'] >=25]
print('나이가 25 이상인 행:')
print(filter_df)

나이가 25 이상인 행:
    name  age     city
3  David   32  Houston
4    Eve   29  Phoenix


In [160]:
dfuser1.sort_values(by='age') # 오름차순

name  age         city
2  Charlie   22      Chicago
0    Alice   24     New Yock
1      Bob   24  LOS Angeles
4      Eve   29      Phoenix
3    David   32      Houston

In [162]:
age_series = dfuser1['age']
age_mean =dfuser1['age'].mean()
age_max =dfuser1['age'].max()
age_min =dfuser1['age'].min()
print('나이의 평균:', age_mean)
print('나이의 촤대값:', age_max)
print('나이의 최소값:', age_min)

나이의 평균: 26.2
나이의 촤대값: 32
나이의 최소값: 22
